name: ci

on:
  pull_request:
    branches: [ main, master ]
    types: [opened, synchronize, reopened]
  push:
    branches: [ main, master ]

jobs:
  python:
    uses: nikolareljin/ci-helpers/.github/workflows/python.yml@production
    with:
      working_directory: .
      lint_command: "python -m pip install -r requirements.txt && python -m pip install ruff && ruff check ."
      test_command: "bash scripts/test.sh"
      build_command: "bash scripts/build.sh"
      extra_command: "git submodule update --init --recursive"
